name: Bullfrog Secure Runner
description: Controls outbound traffic (egress) to secure GitHub Actions workflows.

inputs:
  allowed-ips:
    description: "List of allowed IP addresses for outbound connections."
  allowed-domains:
    description: "List of allowed domains for outbound connections."
  dns-policy:
    description: "DNS policy to enforce when egress-policy is set to 'block'. Options: 'allowed-domains-only' (default) or 'any'."
    default: "allowed-domains-only"
  egress-policy:
    description: "The egress policy to enforce. Options: 'audit' (default) or 'block'."
    type: string
    default: "audit"
  log-directory:
    description: "Directory to store log files."
    type: string
    default: ${{ runner.temp }}/agent-logs
  local-agent-path:
    description: "Path to a local agent binary to use instead of fetching it from Github. This is useful for testing changes to the agent without releasing it. The path is relative to the root action directory (where this action.yml is located)."
    type: string
    default: ""
  agent-download-base-url:
    description: "Base URL for fetching the agent binary. This is useful for testing changes in a fork. The URL should end with a slash."
    type: string
    default: "https://github.com/bullfrogsec/bullfrog/releases/download/"

runs:
  using: "node20"
  main: "action/dist/main.js"
  post: "action/dist/post.js"
