name: Conventional Commits Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-pr-title:
    runs-on: ubuntu-22.04
    steps:
      - name: Enable egress filtering
        uses: bullfrogsec/bullfrog@v0.3
        with:
          egress-policy: audit
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
