name: Test container escape
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: semgrep/semgrep
    steps:
      - uses: fallard84/bullfrog@docker-action
      - run: semgrep ci
