name: Dynamic use

on:
  push:

jobs:
  validate-action-in-another-workflow:
    runs-on: ubuntu-22.04
    timeout-minutes: 2

    steps:
      - uses: jenseng/dynamic-uses@02f544690a931f3967153cd5f14679cfeb61f830
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          uses: ${{ github.repository }}@v0.6.1
          with: '{"allowed-domains": "www.google.com", "egress-policy": "block"}'

      - name: Make HTTP requests
        run: |
          if ! curl https://www.google.com --output /dev/null; then
            echo 'Expected curl to www.google.com to succeed, but it failed';
            exit 1;
          fi;

          if curl https://www.bing.com --max-time 5 --output /dev/null; then
            echo 'Expected curl to www.bing.com to fail, but it succeeded';
            exit 1;
          fi;
