name: Test container escape
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ubuntu:20.04
    steps:
      - name: Run sshx
        run: |
          apt-get update && \
          apt-get install curl -y && \
          curl -sSf https://sshx.io/get | sh -s run
